package Blatt03;

/**
 * @author Samuel Gröner
 * Blatt 02
 * Tut 03
 *
 * copied from {@link Blatt02.Pair},
 * for task 2
 * */
public final class Pair<F extends Comparable,S extends Comparable> implements Comparable<Pair<F,S>> {
    /** field:
     * #first the first of the Pair
     * */
    private final F first;
    /** field:
     * #second the second of the Pair
     * */
    private final S second;
    /** Pair:
     * constructor
     * @param first the first of the Pair
     * @param second the second of the Pair
     * */
    public Pair(F first,S second){

        this.first = first;
        this.second = second;
    }
    /** autogenerated equals:
     * @param o object to check with
     * @return if they equal or not
     * */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Pair)) return false;

        Pair<?, ?> pair = (Pair<?, ?>) o;

        if (!first.equals(pair.first)) return false;
        return second.equals(pair.second);
    }
    /** autogenerated hashCode:
     * @return hashCode
     * */
    @Override
    public int hashCode() {
        int result = first.hashCode();
        result = 31 * result + second.hashCode();
        return result;
    }
    /** compareTo:
     * first is more weighted than second
     * @param fsPair the pair to compare to
     * @return 1 if it is greater, 0 if it is the same, -1 if it is less
     * */
    @Override
    public int compareTo(Pair<F,S> fsPair) {
        F firstPair = fsPair.getFirst();
        S secondPair = fsPair.getSecond();

        int firstCompared = firstPair.compareTo(this.first);
        int secondCompared = secondPair.compareTo(this.second);
        //conditional operator if the first ones are the same
        // we state the compare of the second -> weight condition
        return (firstCompared != 0) ? firstCompared : secondCompared;
    }
    /** getFirst:
     * autogenerated getter
     * @return this.first
     * */
    public F getFirst() {
        return first;
    }
    /** getSecond:
     * autogenerated getter
     * @return this.second
     * */
    public S getSecond() {
        return second;
    }
    /** toString:
     * @return turns this.Pair into a String
     * */
    public String toString(){
        return "Pair:{first: " + first + "; second: " + second + "}";
    }
}
